/*
Script type: DML
Created by: Sohaiba Jee
Created Date: 05/17/2023
Purpose: Inserting data in countries table
*/

USE [IPLVSPSL]

SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;
IF OBJECT_ID('dbo.Countries', 'U') IS NOT NULL
	IF NOT EXISTS (Select * from Countries)
	BEGIN
		INSERT INTO Countries
		([Name], Abbreviation)
		VALUES
		('Afghanistan', 'AFG'),
		('Albania', 'ALB'),
		('Algeria', 'ALG'),
		('American Samoa', 'ASA'),
		('Andorra', 'AND'),
		('Angola', 'ANG'),
		('Anguilla', 'AIA'),
		('Antigua and Barbuda', 'ATG'),
		('Argentina', 'ARG'),
		('Armenia', 'ARM'),
		('Aruba', 'ARU'),
		('Australia', 'AUS'),
		('Austria', 'AUT'),
		('Azerbaijan', 'AZE'),
		('Bahrain', 'BHR'),
		('Bangladesh', 'BAN'),
		('Barbados', 'BAR'),
		('Belarus', 'BLR'),
		('Belgium', 'BEL'),
		('Belize', 'BLZ'),
		('Benin', 'BEN'),
		('Bermuda', 'BER'),
		('Bhutan', 'BHU'),
		('Bolivia', 'BOL'),
		('Bonaire, Sint Eustatius and Saba', 'BES'),
		('Bosnia and Herzegovina', 'BIH'),
		('Botswana', 'BOT'),
		('Brazil', 'BRA'),
		('British Virgin Islands', 'IVB'),
		('Brunei', 'BRU'),
		('Bulgaria', 'BUL'),
		('Burkina Faso', 'BFA'),
		('Burundi', 'BDI'),
		('Cabo Verde', 'CPV'),
		('Cambodia', 'CAM'),
		('Cameroon', 'CMR'),
		('Canada', 'CAN'),
		('Cayman Islands', 'CAY'),
		('Central African Republic', 'CAF'),
		('Chad', 'CHA'),
		('Chile', 'CHI'),
		('China', 'CHN'),
		('Christmas Island', 'CXR'),
		('Colombia', 'COL'),
		('Comoros', 'COM'),
		('Congo (Brazzaville)', 'CGO'),
		('Congo (Kinshasa)', 'COD'),
		('Cook Islands', 'COK'),
		('Costa Rica', 'CRC'),
		('Côte d''Ivoire', 'CIV'),
		('Croatia', 'CRO'),
		('Cuba', 'CUB'),
		('Curaçao', 'CUW'),
		('Cyprus', 'CYP'),
		('Czechia', 'CZE'),
		('Denmark', 'DEN'),
		('Djibouti', 'DJI'),
		('Dominica', 'DMA'),
		('Dominican Republic', 'DOM'),
		('Ecuador', 'ECU'),
		('Egypt', 'EGY'),
		('El Salvador', 'ESA'),
		('Equatorial Guinea', 'GEQ'),
		('Eritrea', 'ERI'),
		('Estonia', 'EST'),
		('Ethiopia', 'ETH'),
		('Falkland Islands (Islas Malvinas)', 'FLK'),
		('Faroe Islands', 'FRO'),
		('Federated States of Micronesia', 'FSM'),
		('Fiji', 'FIJ'),
		('Finland', 'FIN'),
		('France', 'FRA'),
		('French Guiana', 'GUF'),
		('French Polynesia', 'PYF'),
		('Gabon', 'GAB'),
		('Gaza Strip', 'GAZ'),
		('Georgia', 'GEO'),
		('Germany', 'GER'),
		('Ghana', 'GHA'),
		('Gibraltar', 'GIB'),
		('Greece', 'GRE'),
		('Greenland', 'GRL'),
		('Grenada', 'GRN'),
		('Guadeloupe', 'GLP'),
		('Guam', 'GUM'),
		('Guatemala', 'GUA'),
		('Guinea', 'GUI'),
		('Guinea-Bissau', 'GNB'),
		('Guyana', 'GUY'),
		('Haiti', 'HAI'),
		('Honduras', 'HON'),
		('Hong Kong', 'HKG'),
		('Hungary', 'HUN'),
		('Iceland', 'ISL'),
		('India', 'IND'),
		('Indonesia', 'INA'),
		('Iran', 'IRN'),
		('Iraq', 'IRQ'),
		('Ireland', 'IRE'),
		('Isle Of Man', 'IOM'),
		('Israel', 'ISR'),
		('Italy', 'ITA'),
		('Jamaica', 'JAM'),
		('Japan', 'JPN'),
		('Jersey', 'JER'),
		('Jordan', 'JOR'),
		('Kazakhstan', 'KAZ'),
		('Kenya', 'KEN'),
		('Kiribati', 'KIR'),
		('Kosovo', 'KOS'),
		('Kuwait', 'KUW'),
		('Kyrgyzstan', 'KGZ'),
		('Laos', 'LAO'),
		('Latvia', 'LAT'),
		('Lebanon', 'LIB'),
		('Lesotho', 'LES'),
		('Liberia', 'LBR'),
		('Libya', 'LBY'),
		('Liechtenstein', 'LIE'),
		('Lithuania', 'LTU'),
		('Luxembourg', 'LUX'),
		('Macau', 'MAC'),
		('Macedonia', 'MKD'),
		('Madagascar', 'MAD'),
		('Malawi', 'MAW'),
		('Malaysia', 'MAS'),
		('Maldives', 'MDV'),
		('Mali', 'MLI'),
		('Malta', 'MLT'),
		('Marshall Islands', 'MHL'),
		('Martinique', 'MTQ'),
		('Mauritania', 'MTN'),
		('Mauritius', 'MRI'),
		('Mayotte', 'MYT'),
		('Mexico', 'MEX'),
		('Moldova', 'MDA'),
		('Monaco', 'MON'),
		('Mongolia', 'MGL'),
		('Montenegro', 'MNE'),
		('Montserrat', 'MSR'),
		('Morocco', 'MAR'),
		('Mozambique', 'MOZ'),
		('Myanmar', 'MYA'),
		('Namibia', 'NAM'),
		('Nauru', 'NRU'),
		('Nepal', 'NEP'),
		('Netherlands', 'NED'),
		('New Caledonia', 'NCL'),
		('New Zealand', 'NZL'),
		('Nicaragua', 'NCA'),
		('Niger', 'NIG'),
		('Nigeria', 'NGA'),
		('Niue', 'NIU'),
		('Norfolk Island', 'NFK'),
		('North Korea', 'PRK'),
		('Northern Mariana Islands', 'MNP'),
		('Norway', 'NOR'),
		('Oman', 'OMA'),
		('Pakistan', 'PAK'),
		('Palau', 'PLW'),
		('Panama', 'PAN'),
		('Papua New Guinea', 'PNG'),
		('Paraguay', 'PAR'),
		('Peru', 'PER'),
		('Philippines', 'PHI'),
		('Pitcairn Islands', 'PCN'),
		('Poland', 'POL'),
		('Portugal', 'POR'),
		('Puerto Rico', 'PUR'),
		('Qatar', 'QAT'),
		('Reunion', 'REU'),
		('Romania', 'ROU'),
		('Russia', 'RUS'),
		('Rwanda', 'RWA'),
		('Saint Barthelemy', 'BLM'),
		('Saint Helena, Ascension, and Tristan da Cunha', 'SHN'),
		('Saint Kitts and Nevis', 'SKN'),
		('Saint Lucia', 'LCA'),
		('Saint Martin', 'SXM'),
		('Saint Pierre and Miquelon', 'SPM'),
		('Saint Vincent and the Grenadines', 'VIN'),
		('Samoa', 'SAM'),
		('San Marino', 'SMR'),
		('Sao Tome and Principe', 'STP'),
		('Saudi Arabia', 'KSA'),
		('Senegal', 'SEN'),
		('Serbia', 'SRB'),
		('Seychelles', 'SEY'),
		('Sierra Leone', 'SLE'),
		('Singapore', 'SGP'),
		('Sint Maarten', 'SXM'),
		('Slovakia', 'SVK'),
		('Slovenia', 'SVN'),
		('Solomon Islands', 'SOL'),
		('Somalia', 'SOM'),
		('South Africa', 'RSA'),
		('South Georgia And South Sandwich Islands', 'SGS'),
		('South Korea', 'KOR'),
		('South Sudan', 'SSD'),
		('Spain', 'ESP'),
		('Sri Lanka', 'SLK'),
		('Sudan', 'SDN'),
		('Suriname', 'SUR'),
		('Svalbard', 'SJM'),
		('Swaziland', 'SWZ'),
		('Sweden', 'SWE'),
		('Switzerland', 'SUI'),
		('Syria', 'SYR'),
		('Taiwan', 'TPE'),
		('Tajikistan', 'TJK'),
		('Tanzania', 'TAN'),
		('Thailand', 'THA'),
		('The Bahamas', 'BAH'),
		('The Gambia', 'GAM'),
		('Timor-Leste', 'TLS'),
		('Togo', 'TOG'),
		('Tonga', 'TGA'),
		('Trinidad and Tobago', 'TRI'),
		('Tunisia', 'TUN'),
		('Turkey', 'TUR'),
		('Turkmenistan', 'TKM'),
		('Turks and Caicos Islands', 'TCA'),
		('Tuvalu', 'TUV'),
		('U.S. Virgin Islands', 'VIR'),
		('Uganda', 'UGA'),
		('Ukraine', 'UKR'),
		('United Arab Emirates', 'UAE'),
		('United Kingdom', 'ENG'),
		('United States', 'USA'),
		('Uruguay', 'URU'),
		('Uzbekistan', 'UZB'),
		('Vanuatu', 'VAN'),
		('Vatican City', 'VAT'),
		('Venezuela', 'VEN'),
		('Vietnam', 'VIE'),
		('Wallis and Futuna', 'WLF'),
		('West Bank', 'WBG'),
		('Yemen', 'YEM'),
		('Zambia', 'ZAM'),
		('Zimbabwe', 'ZIM'),
		('Scotland', 'SCT'),
		('Guernsey', 'GGY');
	END

COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;

    PRINT ERROR_MESSAGE();
END CATCH;