/*
Script type: DML
Created by: Muhammad Ahmad Saleem
Created Date: 05/24/2023
Purpose: Inserting data in venues table
*/

USE [IPLVSPSL]

SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;
IF OBJECT_ID('dbo.VENUES', 'U') IS NOT NULL
	IF NOT EXISTS (Select * from VENUES)
	BEGIN
		INSERT INTO VENUES (CITY, VENUE)  
		VALUES
			('22', 'Sawai Mansingh Stadium'),
			('22', 'Sawai Mansingh Stadium, Jaipur'),
			('61', 'Shaheed Veer Narayan Singh International Stadium'),
			('61', 'Shaheed Veer Narayan Singh International Stadium, Raipur'),
			('243', 'New Close County Cricket Ground, Newport, Isle-of-Wight'),
			('243', 'Spytty Park, Newport'),
			('963', 'Church Street Park'),
			('1227', 'St Helen''s, Swansea'),
			('1411', 'Feroz Shah Kotla'),
			('1411', 'Arun Jaitley Stadium'),
			('1411', 'Arun Jaitley Stadium, Delhi'),
			('1412', 'Guanggong International Cricket Stadium'),
			('1413', 'Wankhede Stadium'),
			('1413', 'Brabourne Stadium'),
			('1413', 'Wankhede Stadium, Mumbai'),
			('1413', 'Brabourne Stadium, Mumbai'),
			('1413', 'Dr DY Patil Sports Academy, Mumbai'),
			('1413', 'Dr DY Patil Sports Academy'),
			('1413', 'BKC Ground'),
			('1413', 'Sharad Pawar Cricket Academy BKC'),
			('1421', 'Shere Bangla National Stadium, Mirpur'),
			('1421', 'Bangabandhu National Stadium, Dhaka'),
			('1421', 'Bangabandhu National Stadium'),
			('1423', 'Eden Gardens'),
			('1423', 'JU Second Campus, Salt Lake'),
			('1423', 'Eden Gardens, Kolkata'),
			('1423', 'Jadavpur University Campus 2nd Ground, Kolkata'),
			('1423', 'Jadavpur University Campus'),
			('1424', 'Asian Institute of Technology Ground'),
			('1424', 'Terdthai Cricket Ground'),
			('1424', 'Terdthai Cricket Ground, Bangkok'),
			('1424', 'Thailand Cricket Ground'),
			('1427', 'St Albans Club, Buenos Aires'),
			('1427', 'Belgrano Athletic Club Ground, Buenos Aires'),
			('1427', 'Hurlingham Club Ground, Buenos Aires'),
			('1428', 'Tafawa Balewa Square Cricket Oval'),
			('1428', 'University of Lagos Cricket Oval'),
			('1430', 'National Stadium'),
			('1430', 'Southend Club Cricket Stadium'),
			('1430', 'National Stadium, Karachi'),
			('1430', 'Southend Club Cricket Stadium, Karachi'),
			('1431', 'M Chinnaswamy Stadium'),
			('1433', 'Kaizuka Cricket Ground'),
			('1438', 'MA Chidambaram Stadium, Chepauk'),
			('1438', 'MA Chidambaram Stadium'),
			('1438', 'MA Chidambaram Stadium, Chepauk, Chennai'),
			('1438', 'SSN College Ground'),
			('1438', 'T I Murugappa Ground'),
			('1438', 'Sri Ramachandra Medical College'),
			('1438', 'IC-Gurunanak College Ground'),
			('1440', 'Gaddafi Stadium'),
			('1440', 'Gaddafi Stadium, Lahore'),
			('1442', 'Wright Cricket Field, Woodley Park'),
			('1442', 'Severn Cricket Field, Woodley Park'),
			('1442', 'Wong Cricket Field, Woodley Park'),
			('1444', 'Kennington Oval'),
			('1444', 'Lord''s'),
			('1444', 'Lord''s, London'),
			('1444', 'Kennington Oval, London'),
			('1447', 'Rajiv Gandhi International Stadium, Uppal'),
			('1447', 'Rajiv Gandhi International Stadium'),
			('1447', 'Rajiv Gandhi International Stadium, Uppal, Hyderabad'),
			('1447', 'Lal Bahadur Shastri Stadium, Hyderabad, Deccan'),
			('1460', 'Kinrara Academy Oval'),
			('1460', 'Royal Selangor Club'),
			('1460', 'Kinrara Oval'),
			('1460', 'Bayuemas Oval'),
			('1460', 'Selangor Turf Club'),
			('1460', 'Kinrara Academy Oval, Kuala Lumpur'),
			('1460', 'Bayuemas Oval, Kuala Lumpur'),
			('1466', 'Maharashtra Cricket Association Stadium'),
			('1466', 'Maharashtra Cricket Association Stadium, Pune'),
			('1466', 'Subrata Roy Sahara Stadium'),
			('1466', 'Nehru Stadium, Poona'),
			('1466', 'Nehru Stadium'),
			('1467', 'Narendra Modi Stadium'),
			('1467', 'Narendra Modi Stadium, Ahmedabad'),
			('1467', 'Sardar Patel (Gujarat) Stadium, Motera'),
			('1467', 'Sardar Patel Stadium'),
			('1467', 'Sardar Patel Stadium, Motera'),
			('1467', 'Narendra Modi Stadium Ground ''A'', Motera'),
			('1468', 'New Wanderers Stadium, Johannesburg'),
			('1468', 'The Wanderers Stadium'),
			('1468', 'The Wanderers Stadium, Johannesburg'),
			('1468', 'New Wanderers Stadium'),
			('1475', 'Mission Road Ground, Mong Kok'),
			('1475', 'Hong Kong Cricket Club'),
			('1483', 'Zahur Ahmed Chowdhury Stadium, Chittagong'),
			('1483', 'Zahur Ahmed Chowdhury Stadium, Chattogram'),
			('1483', 'MA Aziz Stadium, Chittagong'),
			('1483', 'MA Aziz Stadium'),
			('1487', 'Lalbhai Contractor Stadium'),
			('1487', 'C B Patel Ground'),
			('1487', 'Lalabhai Contractor Stadium'),
			('1497', 'Indian Association Ground'),
			('1497', 'Indian Association Ground, Singapore'),
			('1497', 'Kallang Ground'),
			('1497', 'The Padang'),
			('1497', 'Singapore Cricket Club'),
			('1514', 'Gymkhana Club Ground'),
			('1514', 'Jaffery Sports Club Ground'),
			('1514', 'Gymkhana Club Ground, Nairobi'),
			('1514', 'Ruaraka Sports Club Ground'),
			('1522', 'Toronto Cricket, Skating and Curling Club'),
			('1546', 'Sydney Cricket Ground'),
			('1546', 'Sydney Showground Stadium'),
			('1546', 'North Sydney Oval'),
			('1546', 'North Sydney Oval No.2'),
			('1546', 'Howell Oval'),
			('1546', 'Hurstville Oval'),
			('1546', 'Blacktown International Sportspark'),
			('1546', 'North Sydney Oval, Sydney'),
			('1546', 'Bankstown Oval'),
			('1546', 'Drummoyne Oval'),
			('1546', 'Drummoyne Oval, Sydney'),
			('1546', 'Bankstown Oval, Sydney'),
			('1546', 'Blacktown International Sportspark, Sydney'),
			('1546', 'Stadium Australia'),
			('1546', 'Waverley Oval'),
			('1555', 'Melbourne Cricket Ground'),
			('1555', 'Docklands Stadium'),
			('1555', 'Casey Fields No. 4'),
			('1555', 'Camberwell Sports Ground'),
			('1555', 'Junction Oval'),
			('1555', 'Junction Oval, Melbourne'),
			('1555', 'Docklands Stadium, Melbourne'),
			('1616', 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium'),
			('1616', 'Bharat Ratna Shri Atal Bihari Vajpai Ekana Cricket Stadium'),
			('1616', 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow'),
			('1616', 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium B'),
			('1621', 'Dubai International Cricket Stadium'),
			('1621', 'ICC Academy'),
			('1621', 'ICC Global Cricket Academy'),
			('1621', 'ICC Academy Ground No 2'),
			('1621', 'ICC Academy, Dubai'),
			('1621', 'ICC Academy Ground No 2, Dubai'),
			('1621', 'ICC Academy Oval 2'),
			('1621', 'ICC Academy Oval 1'),
			('1621', 'Dubai Sports City Cricket Stadium'),
			('1631', 'Iqbal Stadium'),
			('1631', 'Iqbal Stadium, Faisalabad'),
			('1648', 'Sulabiya Ground'),
			('1648', 'Tack-Tec Ground'),
			('1656', 'Yeonhui Cricket Ground'),
			('1658', 'Edgbaston'),
			('1658', 'Edgbaston, Birmingham'),
			('1658', 'Edgbaston Foundation Community Sports Ground, Birmingham'),
			('1658', 'Mitchells and Butlers'' Ground, Birmingham'),
			('1679', 'Old Trafford'),
			('1679', 'Old Trafford, Manchester'),
			('1731', 'Vidarbha Cricket Association Stadium, Jamtha'),
			('1731', 'Vidarbha Cricket Association Stadium, Jamtha, Nagpur'),
			('1731', 'Vidarbha C.A. Ground'),
			('1731', 'Vidarbha Cricket Association Ground'),
			('1731', 'VCA Ground'),
			('1738', 'Brisbane Cricket Ground, Woolloongabba'),
			('1738', 'Allan Border Field'),
			('1738', 'Allan Border Field, Brisbane'),
			('1738', 'Brisbane Cricket Ground, Woolloongabba, Brisbane'),
			('1738', 'Brisbane Cricket Ground'),
			('1738', 'Peter Burge Oval'),
			('1743', 'Khettarama Stadium'),
			('1743', 'Sinhalese Sports Club Ground'),
			('1743', 'R Premadasa Stadium'),
			('1743', 'P Sara Oval'),
			('1743', 'Mercantile Cricket Association Ground'),
			('1743', 'Nondescripts Cricket Club Ground'),
			('1743', 'Colombo Cricket Club Ground'),
			('1743', 'R.Premadasa Stadium, Khettarama'),
			('1743', 'Colts Cricket Club Ground'),
			('1743', 'R Premadasa Stadium, Colombo'),
			('1743', 'P Sara Oval, Colombo'),
			('1743', 'R.Premadasa Stadium'),
			('1743', 'P Saravanamuttu Stadium'),
			('1743', 'Sinhalese Sports Club Ground, Colombo'),
			('1743', 'Sinhalese Sports Club'),
			('1760', 'Harare Sports Club'),
			('1760', 'Old Hararians Sports Club'),
			('1760', 'Old Hararians'),
			('1760', 'Takashinga Sports Club'),
			('1760', 'Takashinga Sports Club, Highfield, Harare'),
			('1760', 'Old Hararians, Harare'),
			('1760', 'Sunrise Sports Club, Harare'),
			('1761', 'Kowloon Cricket Club'),
			('1763', 'Western Australia Cricket Association Ground'),
			('1763', 'W.A.C.A. Ground'),
			('1763', 'Lilac Hill Park'),
			('1763', 'Perth Stadium'),
			('1763', 'Western Australia Cricket Association Ground, Perth'),
			('1763', 'Lilac Hill Park, Perth'),
			('1764', 'Morodok Techo National Stadium'),
			('1769', 'Rawalpindi Cricket Stadium'),
			('1773', 'Reliance Stadium'),
			('1773', 'Indian Petrochemicals Corporation Limited Sports Complex Ground'),
			('1773', 'Motibaug Cricket Ground'),
			('1773', 'F B Colony Ground'),
			('1773', 'Reliance Cricket Stadium'),
			('1773', 'Alembic 2  Cricket Ground'),
			('1773', 'Alembic 1 Cricket Ground'),
			('1786', 'Holkar Cricket Stadium'),
			('1786', 'Holkar Stadium'),
			('1786', 'Emerald Heights International School Ground'),
			('1786', 'Holkar Cricket Stadium, Indore'),
			('1786', 'Maharani Usharaje Trust Cricket Ground'),
			('1791', 'Arbab Niaz Stadium'),
			('1805', 'Moara Vlasiei Cricket Ground'),
			('1807', 'Multan Cricket Stadium'),
			('1840', 'Lugogo Cricket Oval'),
			('1840', 'Kyambogo Cricket Oval'),
			('1840', 'Lugogo Cricket Oval, Kampala'),
			('1840', 'Kyambogo Cricket Ground, Kampala'),
			('1857', 'Skarpnack 1'),
			('1857', 'Skarpnack 2'),
			('1869', 'Keenan Stadium'),
			('1872', 'National Sports Academy, Sofia'),
			('1891', 'Sheikh Zayed Stadium'),
			('1891', 'Tolerance Oval'),
			('1891', 'Sheikh Zayed Stadium, Abu Dhabi'),
			('1891', 'Zayed Cricket Stadium'),
			('1891', 'Zayed Cricket Stadium, Abu Dhabi'),
			('1891', 'Tolerance Oval, Abu Dhabi'),
			('1891', 'Sheikh Zayed Stadium Nursery 1'),
			('1891', 'Abu Dhabi Oval 1'),
			('1891', 'Sheikh Zayed Stadium Nursery 2'),
			('1891', 'Abu Dhabi Oval 2'),
			('1907', 'Sheikh Abu Naser Stadium'),
			('1907', 'Sheikh Abu Naser Stadium, Khulna'),
			('1911', 'Nahar Singh Stadium'),
			('1911', 'Nahar Singh Stadium, Faridabad'),
			('1919', 'Lisicji Jarak Cricket Ground'),
			('1925', 'Eden Park'),
			('1925', 'Eden Park No 2'),
			('1925', 'Eden Park Outer Oval'),
			('1925', 'Eden Park, Auckland'),
			('1925', 'Eden Park Outer Oval, Auckland'),
			('1929', 'Saurashtra Cricket Association Stadium'),
			('1929', 'Saurashtra Cricket Association Stadium, Rajkot'),
			('1929', 'Madhavrao Scindia Cricket Ground'),
			('1930', 'Scott Page Field, Vinor'),
			('1943', 'Adelaide Oval'),
			('1943', 'Gliderol Stadium'),
			('1943', 'Gliderol Stadium, Adelaide'),
			('1943', 'Karen Rolton Oval'),
			('1943', 'Karen Rolton Oval, Adelaide'),
			('1943', 'Park 25 No 2, Adelaide'),
			('1943', 'Adelaide Oval No. 2'),
			('1957', 'Providence Stadium, Guyana'),
			('1957', 'Guyana National Stadium, Providence'),
			('1964', 'Sharjah Cricket Stadium'),
			('1964', 'Sharjah Cricket Association Stadium'),
			('1981', 'Mombasa Sports Club Ground'),
			('1993', 'Royal Chiangmai Golf Club'),
			('1993', 'Prem Tinsulanonda International School'),
			('1993', 'Gymkhana Club'),
			('1994', 'West End Park International Cricket Stadium, Doha'),
			('1994', 'West End Park International Cricket Stadium'),
			('2000', 'Malahide'),
			('2000', 'Clontarf Cricket Club Ground'),
			('2000', 'Merrion Cricket Club Ground, Dublin'),
			('2000', 'The Village, Malahide'),
			('2000', 'Pembroke Cricket Club, Sandymount, Dublin'),
			('2000', 'YMCA Cricket Club'),
			('2000', 'The Vineyard'),
			('2000', 'The Village, Malahide, Dublin'),
			('2000', 'Pembroke Cricket Club, Sandymount'),
			('2000', 'Castle Avenue'),
			('2000', 'Sydney Parade'),
			('2000', 'Castle Avenue, Dublin'),
			('2000', 'Observatory Lane, Rathmines'),
			('2000', 'Merrion Cricket Club Ground'),
			('2000', 'Clontarf Cricket Club Ground, Dublin'),
			('2000', 'The Hills Cricket Club Ground'),
			('2026', 'Barsapara Cricket Stadium'),
			('2026', 'Barsapara Cricket Stadium, Guwahati'),
			('2026', 'ACA Stadium, Barsapara'),
			('2055', 'JSCA International Stadium Complex'),
			('2055', 'JSCA International Stadium Complex, Ranchi'),
			('2058', 'Captain Roop Singh Stadium'),
			('2058', 'Captain Roop Singh Stadium, Gwalior'),
			('2063', 'Punjab Cricket Association Stadium, Mohali'),
			('2063', 'Punjab Cricket Association IS Bindra Stadium, Mohali'),
			('2063', 'Punjab Cricket Association IS Bindra Stadium'),
			('2063', 'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh'),
			('2063', 'Sector 16 Stadium'),
			('2063', 'Punjab Cricket Association Stadium, Mohali, Chandigarh'),
			('2063', 'Cricket Stadium, Sector-16'),
			('2063', 'GSSS, Sector 26'),
			('2105', 'Mulpani Cricket Ground'),
			('2120', 'LC de Villiers Oval'),
			('2120', 'Sinovich Park, Sinoville'),
			('2120', 'Harlequins'),
			('2125', 'Amini Park'),
			('2125', 'Amini Park, Port Moresby'),
			('2129', 'Sabina Park, Jamaica'),
			('2129', 'Sabina Park, Kingston, Jamaica'),
			('2132', 'Sportpark Westvliet, The Hague'),
			('2132', 'Sportpark Westvliet, Voorburg'),
			('2143', 'Newlands, Cape Town'),
			('2143', 'Newlands'),
			('2146', 'Basin Reserve'),
			('2146', 'Westpac Stadium'),
			('2146', 'Basin Reserve, Wellington'),
			('2146', 'Sky Stadium'),
			('2146', 'Westpac Stadium, Wellington'),
			('2149', 'Manuka Oval'),
			('2149', 'Manuka Oval, Canberra'),
			('2153', 'Wanderers Cricket Ground'),
			('2153', 'Affies Park'),
			('2153', 'United Cricket Club Ground'),
			('2153', 'Wanderers'),
			('2153', 'Wanderers Cricket Ground, Windhoek'),
			('2153', 'United Cricket Club Ground, Windhoek'),
			('2153', 'Centre for Cricket Development Ground, Windhoek'),
			('2159', 'Mangaung Oval, Bloemfontein'),
			('2159', 'Mangaung Oval'),
			('2159', 'Goodyear Park'),
			('2159', 'OUTsurance Oval'),
			('2159', 'Chevrolet Park'),
			('2159', 'Chevrolet Park, Bloemfontein'),
			('2159', 'Goodyear Park, Bloemfontein'),
			('2162', 'Botswana Cricket Association Oval 1'),
			('2162', 'Botswana Cricket Association Oval 2'),
			('2162', 'Botswana Cricket Association Oval 1, Gaborone'),
			('2162', 'Botswana Cricket Association Oval 2, Gaborone'),
			('2169', 'Albert Park 1'),
			('2169', 'Albert Park 2'),
			('2182', 'Kensington Oval, Bridgetown'),
			('2182', 'Kensington Oval, Barbados'),
			('2182', 'Kensington Oval, Bridgetown, Barbados'),
			('2182', 'Kensington Oval'),
			('2187', 'Queen''s Park Oval, Trinidad'),
			('2187', 'Queen''s Park Oval, Port of Spain, Trinidad'),
			('2187', 'Queen''s Park Oval'),
			('2195', 'Faleata Oval No 1'),
			('2195', 'Faleata Oval No 3'),
			('2195', 'Faleata Oval No 2'),
			('2204', 'Arnos Vale Ground, Kingstown, St Vincent'),
			('2204', 'Arnos Vale Ground'),
			('2210', 'Windsor Park, Roseau, Dominica'),
			('2211', 'Warner Park, Basseterre'),
			('2211', 'Warner Park, St Kitts'),
			('2211', 'Warner Park, Basseterre, St Kitts'),
			('2228', 'White Hill Field, Sandys Parish'),
			('2228', 'Bermuda National Stadium'),
			('2228', 'Sea Breeze Oval'),
			('2346', 'Aigburth'),
			('2346', 'Aigburth, Liverpool'),
			('2350', 'The Rose Bowl'),
			('2350', 'The Rose Bowl, Southampton'),
			('2350', 'The Rose Bowl (Nursery)'),
			('2405', 'Headingley'),
			('2405', 'Headingley, Leeds'),
			('2417', 'Trent Bridge'),
			('2417', 'Trent Bridge, Nottingham'),
			('2438', 'City Oval, Pietermaritzburg'),
			('2438', 'City Oval'),
			('2449', 'Greenfield International Stadium'),
			('2449', 'Greenfield International Stadium, Thiruvananthapuram'),
			('2449', 'St''Xavier''s KCA Cricket Ground'),
			('2449', 'Greenfield Stadium'),
			('2530', 'Jawaharlal Nehru Stadium'),
			('2530', 'St  Pauls college ground  Kalamassery'),
			('2543', 'La Manga Club Top Ground'),
			('2543', 'La Manga Club Bottom Ground'),
			('2572', 'Queens Sports Club'),
			('2572', 'Bulawayo Athletic Club'),
			('2572', 'Queens Sports Club, Bulawayo'),
			('2593', 'Kerrydale Oval'),
			('2602', 'Hazelaarweg'),
			('2602', 'Hazelaarweg, Rotterdam'),
			('2613', 'Titwood, Glasgow'),
			('2613', 'Titwood'),
			('2642', 'Barabati Stadium'),
			('2642', 'DRIEMS Ground'),
			('2642', 'Barabati Stadium, Cuttack'),
			('2657', 'Kingsmead, Durban'),
			('2657', 'Kingsmead'),
			('2657', 'Moses Mabhida Stadium'),
			('2685', 'Rajiv Gandhi International Cricket Stadium, Dehradun'),
			('2694', 'County Ground'),
			('2694', 'County Ground, Bristol'),
			('2694', 'The Royal & Sun Alliance County Ground, Bristol'),
			('2805', 'Grace Road'),
			('2805', 'Grace Road, Leicester'),
			('2826', 'Diamond Oval, Kimberley'),
			('2826', 'Diamond Oval'),
			('2826', 'De Beers Diamond Oval'),
			('2826', 'De Beers Diamond Oval, Kimberley'),
			('2841', 'Johor Cricket Academy Oval'),
			('2862', 'Malek Cricket Ground, Ajman'),
			('2871', 'Grange Cricket Club Ground, Raeburn Place'),
			('2871', 'Grange Cricket Club, Raeburn Place'),
			('2871', 'Grange Cricket Club Ground, Raeburn Place, Edinburgh'),
			('2871', 'Myreside'),
			('2871', 'Goldenacre'),
			('2879', 'Sylhet International Cricket Stadium'),
			('2879', 'Sylhet International Cricket Stadium, Academy Ground'),
			('2879', 'Sylhet Stadium'),
			('3063', 'Airforce Complex ground, Palam'),
			('3063', 'Airforce Complex ground, Palam II'),
			('3083', 'Shaheed Chandu Stadium'),
			('3155', 'Hagley Oval'),
			('3155', 'Hagley Oval, Christchurch'),
			('3155', 'Jade Stadium'),
			('3155', 'AMI Stadium'),
			('3155', 'Jade Stadium, Christchurch'),
			('3231', 'Sportpark Maarschalkerweerd'),
			('3231', 'Sportpark Maarschalkerweerd, Utrecht'),
			('3247', 'Pokhara Rangasala'),
			('3344', 'Buffalo Park, East London'),
			('3344', 'Buffalo Park'),
			('3361', 'Instonians Cricket Club, Shaw''s Bridge Lower Ground, Belfast'),
			('3361', 'Church of Ireland Young Men''s Society Cricket Club Ground, Belfast'),
			('3361', 'Civil Service Cricket Club, Stormont'),
			('3361', 'Civil Service Cricket Club, Stormont, Belfast'),
			('3489', 'St George''s Park, Port Elizabeth'),
			('3489', 'St George''s Park'),
			('3792', 'North Dalton Park'),
			('3792', 'North Dalton Park, Wollongong'),
			('3817', 'County Ground, Derby'),
			('4014', 'SuperSport Park, Centurion'),
			('4014', 'SuperSport Park'),
			('4091', 'Bayer Uerdingen Cricket Ground'),
			('4141', 'Mardyke, Cork'),
			('4156', 'Bellerive Oval'),
			('4156', 'Bellerive Oval, Hobart'),
			('4156', 'University Oval, Hobart'),
			('4243', 'Tikkurila Cricket Ground'),
			('4251', 'County Ground, Northampton'),
			('4320', 'Campbell Park, Milton Keynes'),
			('4654', 'Simonds Stadium, South Geelong, Victoria'),
			('4654', 'Geelong Cricket Ground'),
			('4654', 'GMHBA Stadium, South Geelong, Victoria'),
			('4690', 'Clifton Park Ground, York'),
			('4690', 'York Cricket Club'),
			('4742', 'Tony Ireland Stadium, Townsville'),
			('4742', 'Riverway Stadium, Townsville'),
			('4742', 'Tony Ireland Stadium'),
			('4753', 'Seddon Park'),
			('4753', 'Seddon Park, Hamilton'),
			('4753', 'Westpac Park, Hamilton'),
			('4961', 'Asgiriya Stadium'),
			('5015', 'Willowmoore Park, Benoni'),
			('5015', 'Willowmoore Park'),
			('5015', 'Willowmoore Park B Field'),
			('5015', 'Willowmoore Park C Field'),
			('5015', 'Willowmoore Park A Field'),
			('5305', 'Senwes Park, Potchefstroom'),
			('5305', 'Senwes Park'),
			('5305', 'North-West University No1 Ground'),
			('5305', 'Sedgars Park'),
			('5305', 'North West Cricket Stadium, Potchefstroom'),
			('5335', 'Forthill'),
			('5360', 'Cazaly''s Stadium, Cairns'),
			('5360', 'Cazaly''s Stadium'),
			('5360', 'Bundaberg Rum Stadium, Cairns'),
			('5448', 'Stanley Park, Blackpool'),
			('5540', 'Rookwood, Sale'),
			('5569', 'Marrara Cricket Ground'),
			('5569', 'Marrara Cricket Ground, Darwin'),
			('5634', 'County Ground, Hove'),
			('5883', 'FP Fenner''s Ground, Cambridge'),
			('5918', 'Castle Park Cricket Ground, Colchester'),
			('5918', 'Castle Park Cricket Ground'),
			('6015', 'Choice Moosa Stadium, Pearland'),
			('6015', 'Moosa Cricket Stadium, Pearland'),
			('6103', 'County Ground, Chelmsford'),
			('6135', 'College Ground'),
			('6135', 'College Ground, Cheltenham'),
			('6284', 'Sano International Cricket Ground'),
			('6334', 'Boland Park, Paarl'),
			('6334', 'Boland Park'),
			('6334', 'Boland Bank Park'),
			('6334', 'Boland Bank Park, Paarl'),
			('6618', 'Aurora Stadium'),
			('6618', 'Invermay Park'),
			('6618', 'Invermay Park, Launceston'),
			('6618', 'Aurora Stadium, Launceston'),
			('6618', 'University of Tasmania Stadium, Launceston'),
			('6726', 'County Ground, New Road'),
			('6726', 'County Ground, New Road, Worcester'),
			('6777', 'The Saffrons, Eastbourne'),
			('6868', 'Sportpark Het Schootsveld'),
			('6868', 'Sportpark Het Schootsveld 2'),
			('6942', 'University Oval'),
			('6942', 'University Oval, Dunedin'),
			('6942', 'Carisbrook'),
			('6956', 'Galle International Stadium'),
			('7043', 'VRA Ground'),
			('7043', 'VRA Ground, Amstelveen'),
			('7043', 'VRA Cricket Ground'),
			('7075', 'Boughton Hall Cricket Club Ground, Chester'),
			('7224', 'Tribhuvan University International Cricket Ground'),
			('7224', 'Tribhuvan University International Cricket Ground, Kirtipur'),
			('7229', 'Sportpark Thurlede'),
			('7229', 'Sportpark Harga, Schiedam'),
			('7359', 'Rugby School Ground'),
			('7372', 'Fitzherbert Park, Palmerston North'),
			('7423', 'Uxbridge Cricket Club Ground'),
			('7428', 'Central Broward Regional Park Stadium Turf Ground'),
			('7428', 'Central Broward Regional Park Stadium Turf Ground, Lauderhill'),
			('7596', 'North Marine Road Ground, Scarborough'),
			('7596', 'North Marine Road Ground'),
			('7646', 'Haslegrave Ground, Loughborough'),
			('7646', 'Haslegrave Ground'),
			('7700', 'The Cooper Associates County Ground'),
			('7700', 'County Ground, Taunton'),
			('7700', 'The Cooper Associates County Ground, Taunton'),
			('7750', 'McLean Park'),
			('7750', 'McLean Park, Napier'),
			('7902', 'Chester Road North Ground, Kidderminster'),
			('7976', 'The Gnoll, Neath'),
			('8100', 'Cobham Oval (New)'),
			('8100', 'Cobham Oval (New), Whangarei'),
			('8156', 'The Kent County Cricket Ground'),
			('8156', 'Kent County Cricket Ground, Beckenham'),
			('8156', 'Kent County Cricket Ground'),
			('8299', 'Saxton Oval'),
			('8299', 'Saxton Oval, Nelson'),
			('8734', 'Gorse Lane, Grantham'),
			('8763', 'Penrhyn Avenue, Rhos-on-Sea, Colwyn Bay'),
			('8763', 'Colwyn Bay Cricket Club Ground'),
			('9046', 'Welagedara Stadium'),
			('9363', 'Roseworth Terrace, Gosforth'),
			('9497', 'Riverside Ground'),
			('9497', 'Riverside Ground, Chester-le-Street'),
			('9501', 'Lochlands'),
			('9603', 'Merchant Taylors'' School Ground, Northwood'),
			('9603', 'Merchant Taylors'' School Ground'),
			('9779', 'Stellenbosch University 1'),
			('9779', 'Stellenbosch University 2'),
			('10919', 'Mahinda Rajapaksa International Cricket Stadium, Sooriyawewa'),
			('10919', 'Mahinda Rajapaksa International Cricket Stadium, Sooriyawewa, Hambantota'),
			('10995', 'Oakham School Ground'),
			('11807', 'Marsa Sports Club'),
			('12550', 'Eastern Oval'),
			('12550', 'Eastern Oval, Ballarat'),
			('12663', 'Queen Elizabeth II Oval'),
			('12663', 'Dower Park'),
			('12663', 'Canterbury Park'),
			('12663', 'White Hills Oval'),
			('12663', 'Strathfieldsaye'),
			('12740', 'Kwekwe Sports Club'),
			('12827', 'Trafalgar Road Ground, Southport'),
			('13117', 'Bready'),
			('13465', 'Woodbridge Road, Guildford'),
			('13599', 'ACA Stadium,Mangalagiri'),
			('13730', 'Harrup Park'),
			('13730', 'Ray Mitchell Oval, Harrup Park, Mackay'),
			('13730', 'Great Barrier Reef Arena, Mackay'),
			('13802', 'Rangiri Dambulla International Stadium'),
			('13885', 'Entebbe Cricket Oval'),
			('13949', 'Al Amerat Cricket Ground Oman Cricket (Ministry Turf 1)'),
			('13949', 'Al Amerat Cricket Ground Oman Cricket (Ministry Turf 2)'),
			('15216', 'St Lawrence Ground'),
			('15216', 'St Lawrence Ground, Canterbury'),
			('15397', 'Pukekura Park'),
			('15397', 'Pukekura Park, New Plymouth'),
			('15692', 'Cricket Field Road Ground, Horsham'),
			('17691', 'New Williamfield No1 Oval'),
			('18409', 'Kerava National Cricket Ground'),
			('19807', 'Royal Brussels Cricket Club Ground, Waterloo'),
			('21169', 'West Park Oval'),
			('21437', 'International Sports Stadium'),
			('21437', 'International Sports Stadium, Coffs Harbour'),
			('22117', 'Bready Cricket Club, Magheramason'),
			('22269', 'Gucherre Cricket Ground'),
			('22269', 'Santarem Cricket Ground'),
			('23080', 'Traeger Park, Alice Springs'),
			('23080', 'Traeger Park'),
			('24198', 'Old Deer Park'),
			('24279', 'Daren Sammy National Cricket Stadium, St Lucia'),
			('24279', 'Darren Sammy National Cricket Stadium, St Lucia'),
			('24279', 'Daren Sammy National Cricket Stadium, Gros Islet, St Lucia'),
			('24279', 'Daren Sammy National Cricket Stadium'),
			('26946', 'Desert Springs Cricket Ground'),
			('26946', 'Desert Springs Cricket Ground, Almeria'),
			('27440', 'Louth Cricket Club'),
			('27458', 'Ovale di Rastignano'),
			('28249', 'Centro Sportivo Ca''Nova'),
			('32262', 'Maple Leaf North-West Ground, King City'),
			('32262', 'Maple Leaf North-East Ground, King City'),
			('32262', 'Maple Leaf North-West Ground'),
			('32262', 'Maple Leaf South-West Ground'),
			('32376', 'Coolidge Cricket Ground, Antigua'),
			('32923', 'Sir Vivian Richards Stadium, North Sound'),
			('32923', 'Coolidge Cricket Ground'),
			('32923', 'Antigua Recreation Ground, St John''s'),
			('33405', 'National Cricket Stadium, St George''s'),
			('34364', 'Star Stile'),
			('36425', 'Bradman Oval, Bowral'),
			('36425', 'Bradman Oval'),
			('36835', 'Queen''s Park'),
			('36835', 'Queen''s Park, Chesterfield'),
			('41103', 'Ted Summerton Reserve'),
			('41103', 'Ted Summerton Reserve, Moe'),
			('41599', 'Lavington Sports Oval'),
			('41599', 'Lavington Sports Oval, Albury'),
			('42592', 'Arundel Castle Cricket Club Ground'),
			('42593', 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium'),
			('42593', 'Dr. Y.S. Rajasekhara Reddy ACA VDCA Cricket Stadium'),
			('42593', 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam'),
			('42593', 'Andhra Cricket Association-Visakhapatnam District Cricket Association Stadium'),
			('42593', 'Gokaraju Liala Gangaaraju ACA Cricket Ground'),
			('42594', 'Dr P.V.G. Raju ACA Sports Complex'),
			('42595', 'Carrara Oval'),
			('42596', 'Dr. Gokaraju Laila Ganga Raju ACA Cricket Complex -DVR Ground,Mulapadu'),
			('42596', 'Dr. Gokaraju Laila Ganga Raju ACA Cricket Complex -CP Ground,Mulapadu'),
			('42597', 'Mannofield Park'),
			('42597', 'Mannofield Park, Aberdeen'),
			('42598', 'Cambusdoon New Ground, Ayr'),
			('42598', 'Cambusdoon New Ground'),
			('42599', 'Bert Sutcliffe Oval'),
			('42600', 'John Davies Oval, Queenstown'),
			('42600', 'John Davies Oval'),
			('42600', 'Davies Park, Queenstown'),
			('42600', 'Queenstown Events Centre'),
			('42601', 'Queen''s Park Oval, Port of Spain'),
			('42601', 'Brian Lara Stadium, Tarouba'),
			('42602', 'Simonds Stadium, South Geelong'),
			('42604', 'Molyneux Park'),
			('42605', 'UKM Cricket Oval'),
			('42606', 'UKM-YSD Cricket Oval'),
			('42606', 'UKM-YSD Cricket Oval, Bangi'),
			('42607', 'M.Chinnaswamy Stadium'),
			('42607', 'M Chinnaswamy Stadium, Bengaluru'),
			('42607', 'M Chinnaswamy Stadium, Bangalore'),
			('42679', 'Somerset Cricket Club'),
			('42678', 'Lords, St David''s Cricket Club Ground'),
			('42608', 'Cricket Field Lane'),
			('42609', 'Bready Cricket Club, Magheramason, Bready'),
			('42610', 'Svanholm Park, Brondby'),
			('42611', 'Sophia Gardens'),
			('42611', 'Sophia Gardens, Cardiff'),
			('42612', 'King George V Sports Ground'),
			('42613', 'Zahur Ahmed Chowdhury Stadium'),
			('42613', 'Zohur Ahmed Chowdhury Stadium'),
			('42614', 'Hare Field'),
			('42615', 'The Green, Comber'),
			('42616', 'Sheikh Kamal International Cricket Stadium'),
			('42617', 'Friendship Oval'),
			('42618', 'Rajiv Gandhi International Cricket Stadium'),
			('42619', 'Himachal Pradesh Cricket Association Stadium, Dharamsala'),
			('42620', 'Himachal Pradesh Cricket Association Stadium'),
			('42621', 'Windsor Park, Roseau'),
			('42622', 'Woodvale Road, Eglinton'),
			('42623', 'Happy Valley Ground'),
			('42624', 'Khan Shaheb Osman Ali Stadium'),
			('42624', 'Narayanganj Osmani Stadium'),
			('42625', 'Ashlyns Road'),
			('42626', 'Chilaw Marians Cricket Club Ground'),
			('42627', 'Meersen, Gent'),
			('42628', 'St George''s Park, Gqeberha'),
			('42629', 'Greater Noida Sports Complex Ground'),
			('42630', 'Providence Stadium'),
			('42631', 'Moara Vlasiei Cricket Ground, Ilfov County'),
			('42632', 'Sabina Park, Kingston'),
			('42633', 'Green Park'),
			('42633', 'Green Park, Kanpur'),
			('42634', 'FTZ Sports Complex (BOI)'),
			('42635', 'Kibworth Cricket Club Ground'),
			('42636', 'Integrated Polytechnic Regional Centre'),
			('42636', 'Gahanga International Cricket Stadium, Rwanda'),
			('42637', 'Guttsta Wicked Cricket Club'),
			('42638', 'Latrobe Recreation Ground, Latrobe'),
			('42639', 'Seebarn Cricket Centre, Lower Austria'),
			('42639', 'Seebarn Cricket Centre'),
			('42640', 'Nehru Stadium, Fatorda'),
			('42641', 'Welbeck Colliery Cricket Club Ground, Market Warsop'),
			('42642', 'Shere Bangla National Stadium'),
			('42642', 'Sher-e-Bangla National Cricket Stadium'),
			('42643', 'Mission Road Ground, Mong Kok, Hong Kong'),
			('42644', 'Bay Oval'),
			('42644', 'Bay Oval, Mount Maunganui'),
			('42645', 'Reforma Athletic Club, Naucalpan'),
			('42646', 'Centro Sportivo Dozza'),
			('42647', 'The John Fretwell Sporting Complex, Nettleworth'),
			('42648', 'Sir Vivian Richards Stadium'),
			('42648', 'Sir Vivian Richards Stadium, Antigua'),
			('42648', 'Sir Vivian Richards Stadium, North Sound, Antigua'),
			('42649', 'Nuriootpa Centennial Park'),
			('42650', 'Pallekele International Cricket Stadium'),
			('42651', 'Ground 1, Independence Park'),
			('42651', 'Ground 2, Independence Park'),
			('42651', 'Independence Park, Port Vila'),
			('42652', 'Radlett Cricket Club, Radlett'),
			('42652', 'Radlett Cricket Club'),
			('42652', 'Brunton Memorial Ground, Radlett'),
			('42653', 'Mainpower Oval'),
			('42654', 'Gahanga International Cricket Stadium. Rwanda'),
			('42655', 'Sedbergh School'),
			('42655', 'The Cricket Field, Sedbergh School'),
			('42656', 'Niaz Stadium, Hyderabad'),
			('42657', 'Garon Park'),
			('42658', 'FB Fields'),
			('42659', 'National Cricket Stadium, Grenada'),
			('42659', 'National Cricket Stadium, St George''s, Grenada'),
			('42659', 'Queen''s Park (New), St George''s, Grenada'),
			('42659', 'National Cricket Stadium'),
			('42660', 'Antigua Recreation Ground'),
			('42660', 'Antigua Recreation Ground, St John''s, Antigua'),
			('42661', 'Daren Sammy National Cricket Stadium, Gros Islet'),
			('42661', 'Darren Sammy National Cricket Stadium, Gros Islet'),
			('42661', 'Beausejour Stadium, Gros Islet'),
			('42662', 'Farmers Cricket Club Ground, St Martin'),
			('42662', 'Farmers Cricket Club Ground'),
			('42663', 'College Field'),
			('42663', 'College Field, St Peter Port'),
			('42664', 'Grainville, St Saviour'),
			('42664', 'Grainville'),
			('42665', 'Arnos Vale Ground, Kingstown'),
			('42666', 'New Strabane Park'),
			('42667', 'Brian Lara Stadium, Tarouba, Trinidad'),
			('42668', 'Nevill Ground, Tunbridge Wells'),
			('42668', 'Nevill Ground'),
			('42669', 'Sportpark Westvliet'),
			('42669', 'Sportpark Duivesteijn'),
			('42670', 'Pierre Werner Cricket Ground'),
			('42671', 'Welbeck Abbey Cricket Ground'),
			('42672', 'Sir Paul Getty''s Ground, Wormsley'),
			('42672', 'Sir Paul Getty''s Ground'),
			('42607', 'Alur Cricket Stadium'),
			('42607', 'Alur Cricket Stadium II'),
			('42607', 'Alur Cricket Stadium III'),
			('42673', 'Gurugram Cricket Ground (SRNCC)'),
			('42674', 'Chaudhry Bansi Lal Cricket Stadium'),
			('42613', 'Chittagong Divisional Stadium'),
			('42675', 'Sheikhupura Stadium'),
			('42676', 'Al Dhaid Cricket Village'),
			('42677', 'West Mersea Cricket Club');
	END

COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;

    PRINT ERROR_MESSAGE();
END CATCH;